service: library

# Uncomment the below line for local development
useDotenv: true

provider:
  name: google
  stage: dev
  runtime: nodejs14
  region: ${env:GCP_REGION}
  project: ${env:GCP_PROJECT}
  credentials: ${env:GCP_CREDENTIALS_PATH}

frameworkVersion: '3'

custom:
  dotenv:
    exclude:
      - FAUNADB_DOMAIN
      - FAUNADB_SECRET

plugins:
  - serverless-dotenv-plugin
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.serverless/**'

functions:
  createBook:
    handler: createBook
    events:
      - http: path
    labels:
      project: library
      component: serverless-api
      environment: ${opt:stage}
  getBooks:
    handler: getBooks
    events:
      - http: path
    labels:
      project: library
      component: serverless-api
      environment: ${opt:stage}
