service: cloud-functions

provider:
  name: google
  stage: dev
  runtime: nodejs14
  region: us-east4
  project: marek-dev-283303
  credentials: ${env:CREDENTIALS_PATH}

frameworkVersion: '3'

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

package:
  patterns:
    - '!.git/**'
    - '!.gitignore'
    - '!.serverless/**'
    - '!node_modules/**'

functions:
  books:
    handler: http
    events:
      - http: path
