export const mockBooks = [
  {
    id: '1',
    acquired: false,
    author: 'David Goldblatt',
    date: '',
    read: [],
    retired: false,
    title: 'The Ball is Round',
  },
  {
    id: '2',
    acquired: true,
    author: '',
    date: '2020-06-28',
    read: [],
    retired: false,
    title: 'Great at Work'
  },
  {
    id: '3',
    acquired: false,
    author: 'Thomas Ricks',
    date: '2013-05-11',
    read: ['Bob'],
    retired: false,
    title: 'Fiasco',
  },
  {
    id: '4',
    acquired: false,
    author: '',
    date: '',
    read: [],
    retired: false,
    title: "The Startup Owner's Manual"
  },
  {
    id: '5',
    acquired: true,
    author: '',
    date: '2020-07-01',
    read: ['Bob'],
    retired: false,
    title: 'Tea Time With Terrorists',
  },
  {
    id: '6',
    acquired: false,
    author: 'Tom Foreman',
    date: '',
    read: ['Alice'],
    retired: true,
    title: 'My Year of Running Dangerously',
  },
  {
    id: '7',
    acquired: false,
    author: 'Albert Camus',
    date: '',
    read: ['Alice'],
    retired: false,
    title: 'The Rebel',
  },
  {
    id: '8',
    acquired: false,
    author: 'Jeff Vandermeer',
    date: '',
    read: ['Alice', 'Bob'],
    retired: false,
    title: 'Annihilation',
  },
  {
    id: '9',
    acquired: false,
    author: 'Mark Bowden',
    date: '',
    read: ['Alice', 'Bob'],
    retired: true,
    title: 'Worm',
  },
];

export const mockReaders = [
  { id: '1', color: 'pink', name: 'Alice' },
  { id: '2', color: 'blue', name: 'Bob' },
];
