name: Deploy Library API to Firebase
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Deploy Serverless API
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository...
        uses: actions/checkout@v2

      - name: Setting up environment...
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Preparing dependency cache...
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installing dependencies...
        run: npm install
        working-directory: functions

      - name: Building...
        run: npm run build
        working-directory: functions
        env:
          API_ALLOWED_ORIGIN: ${{ secrets.API_ALLOWED_ORIGIN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_SCOPE: ${{ secrets.AUTH0_SCOPE }}
          FIRESTORE_DB_NAME: ${{ secrets.FIRESTORE_DB_NAME }}
          FIRESTORE_PROJECT: ${{ secrets.FIRESTORE_PROJECT }}
          FIRESTORE_SA: ${{ secrets.FIRESTORE_SA }}

      - name: Deploying to Firebase...
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project ${{ secrets.FIRESTORE_PROJECT }}
        env:
          API_ALLOWED_ORIGIN: ${{ secrets.API_ALLOWED_ORIGIN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_SCOPE: ${{ secrets.AUTH0_SCOPE }}
          FIRESTORE_DB_NAME: ${{ secrets.FIRESTORE_DB_NAME }}
          FIRESTORE_PROJECT: ${{ secrets.FIRESTORE_PROJECT }}
          FIRESTORE_SA: ${{ secrets.FIRESTORE_SA }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
